name: Tests
on: [push, pull_request]

jobs:
  Windows:
    name: windows-${{ matrix.os-version }}-${{ matrix.build-config }}-${{ matrix.build-arch }}
    runs-on: windows-${{ matrix.os-version }}
    strategy:
      fail-fast: false
      matrix:
        os-version: [2019]
        build-config: [debug, release]
        build-arch: [x64]

    steps:
    - uses: actions/checkout@v1

    - name: Configure
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -A${{ matrix.build-arch }} -DCMAKE_BUILD_TYPE=${{ matrix.build-config }} ..

    - name: Build
      shell: bash
      run: |
        cd build
        cmake --build . --config ${{ matrix.build-config }}

    - name: Run (bash)
      shell: bash
      run: |
        cd build/result/${{ matrix.build-config }}
        echo './wintime echo hello'
        ./wintime echo hello
        echo './wintime bash -c "sleep 5"'
        ./wintime bash -c "sleep 5"

    - name: Run (cmd)
      shell: cmd
      run: |
        cd build/result/${{ matrix.build-config }}
        echo 'wintime.exe cmd /C echo "hello"'
        wintime.exe cmd /C echo "hello"

